### ISSUE TITLE
Python2 an Python3 issues with cp and mirror

### ISSUE THREAD

**Issue by jporcelg** [rgs1/zk_shell#112]
**Context**

Debian Stretch, running python 2.7.13 and python 3.5.3 with zk-shell (1.2.3) installed via pip.

**Issue 1**

When doing a (recursive) cp or using mirror it stack traces. For example:

``` 
cp /src/foo /dst/bar true false false true 0
```
zk-shell fails with
```
Traceback (most recent call last):
  File "/usr/local/bin/zk-shell", line 22, in <module>
    CLI()()
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/cli.py", line 165, in __call__
    shell.run(intro if first else None)
  File "/usr/local/lib/python2.7/dist-packages/xcmd/xcmd.py", line 423, in run
    self.cmdloop()
  File "/usr/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/usr/local/lib/python2.7/dist-packages/xcmd/xcmd.py", line 199, in wrapper
    return func(args[0], params)
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/shell.py", line 625, in do_mirror
    self.copy(params, True, True, 0, True)
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/shell.py", line 675, in copy
    src.copy(dst, recursive, max_items, mirror)
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/copy_util.py", line 219, in copy
    self.do_copy(dst, opname)
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/copy_util.py", line 241, in do_copy
    dst.write_path(self.read_path())
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/copy_util.py", line 328, in write_path
    self.client.create(self.path, path_value.value, acl=acl, makepath=True)
  File "/usr/local/lib/python2.7/dist-packages/zk_shell/xclient.py", line 171, in create
    return super(XClient, self).create(path, value, acl, ephemeral, sequence, makepath)
  File "/usr/local/lib/python2.7/dist-packages/kazoo/client.py", line 943, in create
    sequence=sequence, makepath=makepath, include_data=include_data
TypeError: create_async() got an unexpected keyword argument 'include_data'
```

**Issue 2**

Upgrading to python3 solves the above issue but then the following problem appears when you use `mirror` since it prompts you for yes/no using `raw_input`.

```
Are you sure you want to replace /foo/ with /bar/? [y/n]: Traceback (most recent call last):
  File "/usr/local/bin/zk-shell", line 22, in <module>
    CLI()()
  File "/usr/local/lib/python3.5/dist-packages/zk_shell/cli.py", line 165, in __call__
    shell.run(intro if first else None)
  File "/usr/local/lib/python3.5/dist-packages/xcmd/xcmd.py", line 423, in run
    self.cmdloop()
  File "/usr/lib/python3.5/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib/python3.5/cmd.py", line 217, in onecmd
    return func(arg)
  File "/usr/local/lib/python3.5/dist-packages/xcmd/xcmd.py", line 199, in wrapper
    return func(args[0], params)
  File "/usr/local/lib/python3.5/dist-packages/zk_shell/shell.py", line 626, in do_mirror
    if params.skip_prompt or self.prompt_yes_no(question):
  File "/usr/local/lib/python3.5/dist-packages/xcmd/xcmd.py", line 366, in prompt_yes_no
    return strtobool(raw_input().lower())
NameError: name 'raw_input' is not defined
```

**Expected result**

It should just work out of the box :)

The README says zk-shell is compatible with both Python 2.7 and 3 so not quite sure what is going on, perhaps the first error is related to some dependency, I haven't looked into the code just yet. 

Just writing this issue as a for your information.

**Comment by hmojicag** [comment]
Yeah, same issue using Python 3.6.9 in Ubuntu.

`hmojica@hmojica-VirtualBox:~ $ zk-shell --run-once "mirror /configs zk://10.204.50.154:2181/configs" 10.141.233.94:2181
Are you sure you want to replace zk://10.204.50.154:2181/configs with /configs? [y/n]: Traceback (most recent call last):
  File "/home/hmojica/.local/bin/zk-shell", line 22, in <module>
    CLI()()
  File "/home/hmojica/.local/lib/python3.6/site-packages/zk_shell/cli.py", line 145, in __call__
    rc = 0 if shell.onecmd(params.run_once) == None else 1
  File "/usr/lib/python3.6/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/hmojica/.local/lib/python3.6/site-packages/xcmd/xcmd.py", line 199, in wrapper
    return func(args[0], params)
  File "/home/hmojica/.local/lib/python3.6/site-packages/zk_shell/shell.py", line 626, in do_mirror
    if params.skip_prompt or self.prompt_yes_no(question):
  File "/home/hmojica/.local/lib/python3.6/site-packages/xcmd/xcmd.py", line 366, in prompt_yes_no
    return strtobool(raw_input().lower())
NameError: name 'raw_input' is not defined`

**Comment by rgs1** [comment]
@jporcelg @hmojicag weird, we do this in cli.py:

```
try:
    raw_input
except NameError:
    raw_input = input
```

https://github.com/rgs1/zk_shell/blob/master/zk_shell/cli.py#L14

**Comment by hmojicag** [comment]
Awesome.
Well, I just downgraded my Python to 2.7 and it's working now I'll take you update for future reference.
I use mirror to copy Apache SOLR configsets from one cluster to another, so it's the only command I really use.
 Thanks for your response.

**Comment by rgs1** [comment]
@hmojicag i just uploaded version 1.3.2 that should fix this (for python3):

https://pypi.org/project/zk-shell/

Please lmk if it works.

**Comment by jporcelg** [comment]
I just installed 1.3.2 in a test box, tried both `cp` and `mirror` and they seem to work fine for me now. 

Many thanks :)
