### ISSUE TITLE
intermittent issue with child_count

### ISSUE THREAD

**Issue by gl101** [rgs1/zk_shell#30]
When I run zkshell with the parameters:  --run-once "child_count ."
I sometimes get the following exception

Traceback (most recent call last):
  File "/OMITTED/zk_shell-master/bin/zk-shell", line 22, in <module>
    CLI()()
  File "./zk_shell/cli.py", line 129, in __call__
    rc = 0 if shell.onecmd(params.run_once) == None else 1
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "./zk_shell/shell.py", line 95, in wrapper
    return func(*args, **kwargs)
  File "./zk_shell/xcmd.py", line 148, in wrapper
    return func(*args, **kwargs)
  File "./zk_shell/xcmd.py", line 160, in wrapper
    return func(args[0], params)
  File "./zk_shell/shell.py", line 138, in wrapper
    return func(self, params)
  File "./zk_shell/shell.py", line 732, in do_child_count
    self.show_output("%s: %d", child, self._zk.child_count(child))
  File "./zk_shell/xclient.py", line 251, in child_count
    count = stat.numChildren
AttributeError: 'NoneType' object has no attribute 'numChildren'

This is after some of the top-level directories were correctly summarized.
In the times when the command completes okay (no exception), the count of children on the node which seems to be causing the problem is 0.
I am sorry but I am not able to share the zookeeper data-directory on which this problem occurs.

I am running under Python 2.7.3

**Comment by rgs1** [comment]
Thanks for reporting @gl101, here's the fix:

https://github.com/rgs1/zk_shell/commit/32319de07f36370574d0871028d57c9e5ce972ee

Sorry for missing that one.

**Comment by gl101** [comment]
Hi Raul, Thank you for the quick turnaround on this.
Guy
