### ISSUE TITLE
stack trace after using --tunnel 

### ISSUE THREAD

**Issue by rgs1** [rgs1/zk_shell#34]
Hey @franckcuny ,

I am getting this when using --tunnel after exiting zk-shell (via Ctrl-C, Ctrl-D or exit):

```
$ zk-shell --tunnel opsnest1 sdzookeeper.smf1.twitter.com
Welcome to zk-shell (1.0.08)
(CONNECTING) /> 
(CONNECTED) /> exit

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/twitter/common/net/tunnel.py", line 40, in safe_kill
    po.wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python2.7/site-packages/zk_shell/cli.py", line 88, in sigusr_handler
    raise StateTransition()
StateTransition
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/site-packages/twitter/common/net/tunnel.py", line 40, in safe_kill
    po.wait()
  File "/usr/lib64/python2.7/subprocess.py", line 1376, in wait
    pid, sts = _eintr_retry_call(os.waitpid, self.pid, 0)
  File "/usr/lib64/python2.7/subprocess.py", line 476, in _eintr_retry_call
    return func(*args)
  File "/usr/lib/python2.7/site-packages/zk_shell/cli.py", line 88, in sigusr_handler
    raise StateTransition()
zk_shell.cli.StateTransition
```

Any ideas?

cc: @Yasumoto

**Comment by franckcuny** [comment]
I'm getting a different but similar one

```
Welcome to zk-shell (1.0.08)
(CONNECTING) />
(CONNECTED) /> quit

Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1670, in shutdown
    h.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 713, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1670, in shutdown
    h.release()
  File "/usr/lib/python2.7/logging/__init__.py", line 713, in release
    self.lock.release()
  File "/usr/lib/python2.7/threading.py", line 204, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock
~/src/zk_shell %
```

**Comment by rgs1** [comment]
with --tunnel right?

**Comment by franckcuny** [comment]
yeah with --tunnel.

I'm getting more certain there's a race condition somewhere. There's also a "atexit" hook in the TunnelHelper to kill the tunnel before exiting. If I comment this out I don't get the error anymore.

I'll keep trying to narrow this down today.

**Comment by rgs1** [comment]
might be a kazoo thing: https://github.com/python-zk/kazoo/pull/318

**Comment by franckcuny** [comment]
Hm interesting. I'll have some time this weekend to get another shot at the issue.
