### ISSUE TITLE
get crashes every time.

### ISSUE THREAD

**Issue by oliveagle** [rgs1/zk_shell#54]
```
(CONNECTED) /> get consumers/test_group1/offsets/metric_thrift/0
Traceback (most recent call last):
  File "/usr/bin/zk-shell", line 22, in <module>
    CLI()()
  File "/usr/lib/python2.6/site-packages/zk_shell/cli.py", line 151, in __call__
    shell.run(intro if first else None)
  File "/usr/lib/python2.6/site-packages/zk_shell/xcmd.py", line 250, in run
    self.cmdloop()
  File "/usr/lib64/python2.6/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python2.6/cmd.py", line 219, in onecmd
    return func(arg)
  File "/usr/lib/python2.6/site-packages/zk_shell/shell.py", line 80, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/zk_shell/xcmd.py", line 142, in wrapper
    return func(args[0], params)
  File "/usr/lib/python2.6/site-packages/zk_shell/shell.py", line 123, in wrapper
    return func(self, params)
  File "/usr/lib/python2.6/site-packages/zk_shell/shell.py", line 914, in do_get
    value, _ = self._zk.get(params.path, **kwargs)
  File "/usr/lib/python2.6/site-packages/zk_shell/xclient.py", line 167, in get
    value = value.decode(encoding="utf-8")
TypeError: decode() takes no keyword arguments
```

zookeeper-shell.sh get correct result

```
get /consumers/test_group1/offsets/metric_thrift/0
2977408
cZxid = 0x2449
ctime = Fri Jul 31 10:56:42 CST 2015
mZxid = 0x2558
mtime = Fri Jul 31 11:04:39 CST 2015
pZxid = 0x2449
cversion = 0
dataVersion = 6
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 7
numChildren = 0
```

**Comment by rgs1** [comment]
Python 2.6 is not supported, since it has reached its end of life:

https://mail.python.org/pipermail/python-dev/2013-September/128287.html
