### ISSUE TITLE
ImportError: No module named 'colors'

### ISSUE THREAD

**Issue by blue20080** [rgs1/zk_shell#59]
when run:

# bin/zk-shell 
Traceback (most recent call last):
  File "bin/zk-shell", line 13, in <module>
    from zk_shell.cli import CLI
  File "./zk_shell/cli.py", line 11, in <module>
    from .shell import Shell
  File "./zk_shell/shell.py", line 26, in <module>
    from colors import green, red
ImportError: No module named 'colors'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/zk-shell", line 18, in <module>
    from zk_shell.cli import CLI
  File "./zk_shell/cli.py", line 11, in <module>
    from .shell import Shell
  File "./zk_shell/shell.py", line 26, in <module>
    from colors import green, red
ImportError: No module named 'colors'

Python version is 3.3.0

# python
Python 3.3.0 (default, Nov 17 2015, 23:35:39) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-16)] on linux
Type "help", "copyright", "credits" or "license" for more information.

Who Can help me ?Thanks!

**Comment by gl101** [comment]
I think where it says to do "pip install kazoo", do instead:
pip install -r zk_shell/requirements.txt
This will install all of the dependencies that are needed
