### ISSUE TITLE
du command hangs

### ISSUE THREAD

**Issue by ghost** [rgs1/zk_shell#65]
The scenario:

zookeeper 3.4.6 running in standalone mode
a (java) client connects to it and in a loop performs:
    create /foo
    sleep 100millis
    delete /foo
    sleep 100millis

now to zkshell, here is what I do to reproduce the problem:
# ! /bin/sh

while /bin/true
do
  zkshell --run-once du localhost:2181
done

I sometimes get the correct result

Other times I get the below exception, this occurs quite frequently:
Exception in thread Thread-3 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 763, in run
  File "/home/laden/.pex/install/kazoo-2.2.1-py2.py3-none-any.whl.8c0daadbce7c0827d2ff5c5d7ef717aad64a60a8/kazoo-2.2.1-py2.py3-none-any.whl/kazoo/protocol/connection.py", line 477, in zk_loop
  File "/usr/lib/python2.7/threading.py", line 585, in set
  File "/usr/lib/python2.7/threading.py", line 406, in notifyAll
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

And finally, after a while, zkshell/du hangs. This occurs least often and sometimes take a few mins
Not sure its helpful to mention but when this occurs, control-C does not seem to work to get out of it

**Comment by gl101** [comment]
Looks like the code is hanging because it is blocked on Queue.get,
in zk_shell/usage.py, function get(), the line: "req = reqs.get()"

**Comment by gl101** [comment]
Okay I may be wrong but to me it looks like in usage(), in the while loop,
If a NoNode exception occurs, the code must still take care to decrement pending
